spring:
  datasource:
    url: jdbc:mysql://120.79.18.242/job?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: lilinhai123
#    url: jdbc:mysql://localhost/job?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      auto-commit: true
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: update
      #控制台显示SQL
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    #thymeleaf关闭缓存
    cache: false
    prefix: classpath:/templates
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 100MB